print ("Biodata")

A = str("Mira Yunisa Amalia")
B = str("I0320057")
C = str("B")
D = str("Teknik Industri")
E = str("Teknik")
F = str("Universitas Sebelas Maret")
G = str("Serang, Banten")
H = str("Perempuan")
I = str("Serang, 29 Juni 2002")
J = int("18")
K = float("1.5")
L = int("41")
M = float("37.5")
kedua = True
pertama = False

print ("Data yang harus diisi :")
print ("1. Nama : ", A)
print ("2. NIM : ", B)
print ("3. Kelas : ", C)
print ("4. Program Studi : ", D)
print ("5. Fakultas : ", E)
print ("6. Universitas : ", F)
print ("7. Alamat : ", G)
print ("8. Jenis Kelamin : ", H)
print ("9. Tempat Tanggal Lahir : ", I)
print ("10. Umur : ", J , "tahun")
print ("11. Tinggi Badan : ", K , "m")
print ("12. Barat Badan : ", L , "kg")
print ("13. Nomor Sepatu : ", M)
print ("14. Aku anak kedua", kedua)
print ("14. Aku anak pertama", pertama)
